FROM golang:1.12.4
LABEL stage=intermediate
WORKDIR $GOPATH/src/github.com/albertwidi/k8s-tutorial/frontend
COPY . .
RUN GOOS=linux CGO_ENABLED=0 go build -v -o frontend-bin main.go

FROM alpine:latest
COPY --from=0 /go/src/github.com/albertwidi/k8s-tutorial/frontend/frontend-bin /frontend-bin
ENTRYPOINT /frontend-bin