apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
    version: {{ .Chart.Version }}
spec:
  ports:
    - name: http
      port: {{ .Values.Service.port }}
      protocol: TCP
      targetPort: {{ .Values.Service.targetPort }}
  selector:
    app: {{ .Release.Name }}