version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: k8s-tutor-backend
    command:
    - "-address=127.0.0.1:9000"
    ports:
    - "9000:9000"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: k8s-tutor-frontend
    command:
    - "-address=127.0.0.1:9090"
    ports:
    - "9090:9090"
    depends_on:
    - backend