apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tutorial-backend 
  namespace: tutorial
  labels:
    app: tutorial-backend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: tutorial-backend
  template:
    metadata:
      labels:
        app: tutorial-backend
    spec:
      containers:
      - image: albertwidi/k8s-tutorial-backend:latest
        name: tutorial-backend
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            # when "host" is not defined, "PodIP" will be used
            # host: my-host
            # when "scheme" is not defined, "HTTP" scheme will be used. Only "HTTP" and "HTTPS" are allowed
            # scheme: HTTPS
            path: /healtcheck?probe=liveness
            port: 9000 
          initialDelaySeconds: 15
          timeoutSeconds: 1