apiVersion: v1
kind: Service
metadata:
  name: tutorial-backend
  namespace: tutorial
spec:
  selector:
    app: tutorial-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000
  type: LoadBalancer